export const applicationResponse = {
  applicationId: expect.any(String),
  nationalId: expect.any(String),
  secretWord: expect.any(String),
  getPaperCopy: expect.any(Boolean),
  employmentStatus: expect.any(String),
  employmentRatio: expect.any(Number),
  bank: expect.any(String),
  pensionFundPercentage: expect.any(Number),
  personalTaxCreditRatio: expect.any(Number),
  personalTaxCreditMonthlyAmount: expect.any(Number),
  monthlyIncome: expect.any(Number),
  insurancePayments: expect.any(Number),
  pensionPayments: expect.any(Number),
  incomeStepOne: expect.any(Number),
  incomeStepTwo: expect.any(Number),
  onParentalLeave: expect.any(Boolean),
  unionId: expect.any(String),
  pensionFundId: expect.any(String),
  privatePensionFundId: expect.any(String),
  created: expect.any(String),
  modified: expect.any(String),
}
