version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: national_registry
        APP: services-party-letter-registry-api
    networks:
      - local
    depends_on:
      - national_registry
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=national_registry
    volumes:
      - ../../..:/code

  national_registry:
    ports: []
